;;; based on danranx@gmail.com's color theme tango
(defun color-theme-bmac ()
  "A color theme based on Tango Palette."
  (interactive)
  (color-theme-install
   '(color-theme-bmac
     ((background-color . "#2e3436")
      (background-mode . dark)
      (border-color . "#888a85")
      (cursor-color . "#ffffff")
      (foreground-color . "#eeeeee")
      (mouse-color . "#8ae234"))
     ((help-highlight-face . underline)
      (ibuffer-dired-buffer-face . font-lock-function-name-face)
      (ibuffer-help-buffer-face . font-lock-comment-face)
      (ibuffer-hidden-buffer-face . font-lock-warning-face)
      (ibuffer-occur-match-face . font-lock-warning-face)
      (ibuffer-read-only-buffer-face . font-lock-type-face)
      (ibuffer-special-buffer-face . font-lock-keyword-face)
      (ibuffer-title-face . font-lock-type-face))
     (border ((t (:background "#888a85"))))
     (fringe ((t (:background "grey10"))))
     (mode-line ((t (:foreground "#eeeeec" :background "#555753"))))
     (region ((t (:background "#555753"))))
     (font-lock-builtin-face ((t (:foreground "#729fcf"))))
     (font-lock-comment-face ((t (:foreground "#9fb6cd"))))
     (font-lock-constant-face ((t (:foreground "#00c5cd" :bold t))))
     (font-lock-doc-face ((t (:foreground "#778899"))))
     (font-lock-keyword-face ((t (:foreground "#729fcf" :bold t))))
     (font-lock-string-face ((t (:foreground "#9acd32"))))
     (font-lock-type-face ((t (:foreground "#ee9a49" :bold t))));; caral #ff7256
     (font-lock-variable-name-face ((t (:foreground "#eeeeec"))))
     (font-lock-warning-face ((t (:bold t :foreground "#f57900"))))
     (font-lock-function-name-face ((t (:foreground "#9fb6cd" :bold t)))) ;;orange "#ee7600"
     (comint-highlight-input ((t (:italic t :bold t))))
     (comint-highlight-prompt ((t (:foreground "#8ae234"))))
     (isearch ((t (:background "#7ec0ee" :foreground "#2e3436"))))
     (isearch-lazy-highlight-face ((t (:foreground "white" :background "#4f94cd"))))
     (show-paren-match-face ((t (:foreground "white" :background "#36648b"))))
     (show-paren-mismatch-face ((t (:background "#ad7fa8" :foreground "#2e3436"))))
     (minibuffer-prompt ((t (:foreground "#729fcf" :bold t))))
     (info-xref ((t (:foreground "#729fcf"))))
     (info-xref-visited ((t (:foreground "#ad7fa8"))))
     )))

(provide 'color-theme-bmac)
