;;; mocha-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from mocha.el

(autoload 'mocha-test-project "mocha" "\
Test the current project." t)
(autoload 'mocha-debug-project "mocha" "\
Debug the current project." t)
(autoload 'mocha-test-file "mocha" "\
Test the current file." t)
(autoload 'mocha-debug-file "mocha" "\
Debug the current file." t)
(autoload 'mocha-test-at-point "mocha" "\
Test the current innermost 'it' or 'describe' or the file if none is found." t)
(autoload 'mocha-debug-at-point "mocha" "\
Debug the current innermost 'it' or 'describe' or the file if none is found." t)
(autoload 'mocha-toggle-imenu-function "mocha" "\
Toggle the use mocha-specific imenu function." t)
(register-definition-prefixes "mocha" '("mocha-" "node-error-regexp"))

;;; End of scraped data

(provide 'mocha-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mocha-autoloads.el ends here
